//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noteprice.Bl.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDB : DbContext
    {
        public MainDB()
            : base("name=MainDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<GoodsType> GoodsTypes { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreSet> StoreSets { get; set; }
        public virtual DbSet<vwStoreStoreSet> vwStoreStoreSets { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<vwPriceStore> vwPriceStores { get; set; }
    }
}
