//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noteprice.Bl.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Prices = new HashSet<Price>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<int> StoreSetId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual StoreSet StoreSet { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
    }
}
